name: check config


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

     - name: set up kubeconfig
       env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
       run: echo "$KUBECONFIG_FILE" > kubeconfig

     - name: get nodes
       run: kubectl --kubeconfig=kubeconfig get nodes

    
