name: get_config


on: 
  workflow_dispatch:

jobs:
  to_get_config:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     - name: update kubeconfig
       run: |
          aws eks --region us-east-2 update-kubeconfig --name education-eks-xjCnMVsM

     - name: view kubeconfig
       run: |
          cat /home/runner/.kube/config

     - name: get nodes
       run: |
           kubectl get nodes
