name: Deployment__workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Checkout chrome
       uses: nanasess/setup-chromedriver@master
       
    # - name: install google
     #  run: |
      #    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #  sudo apt install ./google-chrome-stable_current_amd64.deb
        #  sudo apt install google-chrome-stable


   #  - name: install chrome driver
     #  run: |

          #sudo apt install python3.8-venv
        #  source venv/bin/activate
        ##   python ./terraform/testtt.py
          

     - name: run test
       run: |
        
        python ./terraform/testtt.py
          
         
