name: Deployment__workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: install google
       run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          sudo apt install google-chrome-stable


     - name: install chrome driver
       run: |
          mkdir tests
          cd tests
          #sudo apt install python3.8-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install selenium webdriver-manager

          

     - name: run test
       run: |
        python ./terraform/testtt.py
          
         
