name: Deployment__workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: install dep
       run: |
          pip install selenium
          pip install selenium webdriver-manager

     - name: run test
       run: |
          from selenium import webdriver
          from webdriver_manager.microsoft import EdgeChromiumDriverManager

          driver = webdriver.Edge(EdgeChromiumDriverManager().install())

          driver.get("https://www.youtube.com")

          driver.quit()
          
         
