name: Deployment__workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: install dep
       run: |
          pip install selenium
          pip install selenium webdriver-manager

     - name: install chrome driver
       run: |
          sudo apt-get install chromium-chromedriver==119.0.6045.105

          
     
     #- name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
      # uses: nanasess/setup-chromedriver@master

     - name: run test
       run: |
        python ./terraform/testtt.py
          
         
