name: Deployment__workflow


on: 
  workflow_dispatch:
    inputs:
     URL:
        description: Near_url
        required: true
        default: "https://www.python.org"

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Checkout python
       uses: actions/setup-python@v4
       with:
          python-version: '3.x'

     - name: Install pck
       run: apt list --installed

   #  - name: rem chrome and runner prev
     #  run: sudo apt purge google-chrome-stable

     - name: inst pck
       run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

     - name: Install xvfb
       run: sudo apt-get install xvfb
     
       
    # - name: install google
     #  run: |
      #    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #  sudo apt install ./google-chrome-stable_current_amd64.deb
        #  sudo apt install google-chrome-stable


   #  - name: install chrome driver
     #  run: |

          #sudo apt install python3.8-venv
        #  source venv/bin/activate
        ##   python ./terraform/testtt.py

     - name: set url
       id: set-url-env
       run: |
        echo "url=${{ github.event.inputs.URL }}" >> $GITHUB_ENV
        echo "url=${{ github.event.inputs.URL }}" >> $RUNNER_TEMP/env
     - name: run test
       env:
         url: ${{ env.url }}
       run: |
        #pip install selenium==3.141.0
        python ./terraform/testtt.py
          
         
