name: Deployment workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: create disco env 
       run: sh deployment/k8s/create.sh
