name: test11


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
     
     - name: Download ScaleOut-gcc8.4.1-redhat-8-2.4.6-97-PLUGINS from s3
       run: aws s3 cp s3://ghtest-sept23/ScaleOut-gcc8.4.1-redhat-8-2.4.6-97-SDK.tar.gz $GITHUB_WORKSPACE/ScaleOut-gcc8.4.1-redhat-8-2.4.6-97-SDK.tar.gz

     - name: see location
       run: |
          pwd
          ls -ltr

  
