name: Deployment workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest

     env:
       test: version
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: create disco env 
       run: |
         docker $test
