name: delete Deployment workflow


on: 
  workflow_dispatch:

jobs:
  run-scripts:
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up kubectl     
       run: | 
         mkdir -p ~/.kube        
         echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config  
         kubectl version --short
         pwd

     - name: get nodes
       run: kubectl get nodes
